version: "3.8"

services:
  app:
    container_name: app
    image: app-dev
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
    networks:
      app:
        ipv4_address: 172.20.0.2
    volumes:
      - .:/opt
    ports:
      - 7790:7790
    depends_on:
      - mariadb
      - mongodb
    links:
      - mariadb
      - mongodb
  
  mariadb:
    image: mariadb:10.10.2-jammy
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./volumes/database/mysql:/var/lib/mysql
      - ./volumes/sql:/sql
    networks:
      app:
        ipv4_address: 172.20.0.3
    env_file:
      - .env
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-u', 'root', '-p${MARIADB_ROOT_PASSWORD}' ]
      interval: 5s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: always
    env_file:
      - .env
    volumes:
      - ./volumes/database/mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      app:
        ipv4_address: 172.20.0.4

networks:
  app:
    ipam:
      config:
        - subnet: 172.20.0.0/16